# Beispiel aus le1_eigenwerte_und_eigenvektoren.pdf 3.2 (Seite 8)

In [79]:
import numpy as np
import sympy as sp
from sympy.solvers.solveset import linsolve

In [80]:
B = np.array([[0,0,-2],[1,2,1],[1,0,3]])
I = np.eye(3) # Einheitsmatrix

## Manuelles Berechnen der Eigenvektoren und Eigenwerten

In [82]:

l = sp.symbols("l") # l wie lambda
B_1 = sp.Matrix(B) #Matrix als Sympy Matrix definieren, damit mit einer Variable gerechnet werden kann
I_1 = sp.Matrix(I) # Einheitsmatrix as sympy Matrix

# Determinante berechnen
det = sp.det(B_1-l*I_1)

# Werte für lambda berechnen = Eigenwerte, jedoch ohne algebraische Vielfachheit
ew_1 = sp.solve(det)

print(ew_1)



[1.00000000000000, 2.00000000000000]


In [85]:
# Berechnen der Eigenvektoren

def Eigenvektor(ew):
    # Matrix - der erste Eigenwert
    x = B_1 - ew*np.eye(3)
    # Erweiterte Koefizientenmatrix
    y = np.append(x,[[0],[0],[0]],1)
    # LGS lösen
    return linsolve(sp.Matrix(y))

Eigenvektor(ew_1[0])
#Eigenvektor(ew_1[1])

FiniteSet((-2.0*tau0, 1.0*tau0, tau0))

## Berechnung der Eigenvektoren und Eigenwerte mittels Numpy

In [89]:
ew_2, V = np.linalg.eig(B)
print('Eigenwerte: {0}, \n Eigenvektoren: \n {1}'.format(ew_2,V))

Eigenwerte: [2. 1. 2.], 
 Eigenvektoren: 
 [[ 0.         -0.81649658  0.70710678]
 [ 1.          0.40824829  0.        ]
 [ 0.          0.40824829 -0.70710678]]


In [90]:
# Diagonalmatrix der Eigenwerte
D = np.diag(ew_2)
print(D)

[[2. 0. 0.]
 [0. 1. 0.]
 [0. 0. 2.]]


In [91]:
# Berechnung der Inverse von V
Vi = np.linalg.inv(V)

print(Vi)

[[ 1.          1.          1.        ]
 [-2.44948974 -0.         -2.44948974]
 [-1.41421356 -0.         -2.82842712]]


In [92]:
# Nun sollte VDVi = B
V @ D @ Vi

array([[ 4.05861454e-17,  0.00000000e+00, -2.00000000e+00],
       [ 1.00000000e+00,  2.00000000e+00,  1.00000000e+00],
       [ 1.00000000e+00,  0.00000000e+00,  3.00000000e+00]])