# Beispiel aus le1_eigenwerte_und_eigenvektoren.pdf 3.2 (Seite 8)

In [4]:
import numpy as np
import sympy as sp
from sympy.solvers.solveset import linsolve

In [18]:
B = sp.Matrix([[0,0,-2],[1,2,1],[1,0,3]])
B_numpy = np.array([[0,0,-2],[1,2,1],[1,0,3]])


## Manuelles Berechnen der Eigenvektoren und Eigenwerten

In [7]:
# Determinante berechnen
def Eigenwert(m): 
    size = m.shape[0]
    l = sp.symbols("l") # l wie lambda
    I = np.eye(size) # Einheitsmatrix
    I_1 = sp.Matrix(I) # Einheitsmatrix as sympy Matrix
    det = sp.det(m-l*I_1)

    # Werte für lambda berechnen = Eigenwerte, jedoch ohne algebraische Vielfachheit
    return sp.solve(det)

ew = Eigenwert(B)

print(ew)



[1.00000000000000, 2.00000000000000]


In [8]:
# Berechnen der Eigenvektoren
def Eigenvektor(ew,m):
    # Matrix - dem ersten Eigenwert
    M = m - ew*np.eye(m.shape[0])
    # Erweiterte Koeffizientenmatrix
    M = np.append(M,([[0]] * m.shape[0]),1)
    # LGS lösen
    #x,y,z = sp.symbols('x y z')
    return linsolve(sp.Matrix(M))

Eigenvektor(ew[0],B)
#Eigenvektor(ew[1],B)


FiniteSet((-2.0*tau0, 1.0*tau0, tau0))

In [13]:
# Alternativ mit sp.solve

def sp_eigenvektor(ew):
    x,y,z = sp.symbols('x y z')
    return sp.solve((B - ew*np.eye(3))*sp.Matrix([[x],[y],[z]]) )

sp_eigenvektor(ew[0])

# Anschliessend noch Eigenvektoren bestimmen

{x: -2.0*z, y: z}

## Berechnung der Eigenvektoren und Eigenwerte mittels Numpy

In [19]:
ew_2, V = np.linalg.eig(B_numpy)
print('Eigenwerte: {0}, \n Eigenvektoren: \n {1}'.format(ew_2,V))

Eigenwerte: [2. 1. 2.], 
 Eigenvektoren: 
 [[ 0.         -0.81649658  0.70710678]
 [ 1.          0.40824829  0.        ]
 [ 0.          0.40824829 -0.70710678]]


In [20]:
# Diagonalmatrix der Eigenwerte
D = np.diag(ew_2)
print(D)

[[2. 0. 0.]
 [0. 1. 0.]
 [0. 0. 2.]]


In [21]:
# Berechnung der Inverse von V
Vi = np.linalg.inv(V)

print(Vi)

[[ 1.          1.          1.        ]
 [-2.44948974 -0.         -2.44948974]
 [-1.41421356 -0.         -2.82842712]]


In [22]:
# Nun sollte VDVi = B
np.round(V @ D @ Vi)

array([[ 0.,  0., -2.],
       [ 1.,  2.,  1.],
       [ 1.,  0.,  3.]])

# Uebung Aufgabe 15

In [23]:
A = sp.Matrix([[89, 75,22, 102],[75, 116, 27, 120],[22,27,33,62],[102,120,62,200]])
A_numpy = np.array([[89, 75,22, 102],[75, 116, 27, 120],[22,27,33,62],[102,120,62,200]])

In [25]:
# Aufage a
res = Eigenwert(A)

# Umwandung von Complex; runden auf 10 Nachkommastellen 
res_round = [round(complex(i).real,10) for i in res]

print(res_round)

[7.1630569063, 26.3371890658, 42.745931007, 361.7538230209]


In [26]:
# Lösung mit numpy
np.linalg.eig(A_numpy)

(array([361.75382302,  42.74593101,  26.33718907,   7.16305691]),
 array([[-0.42552429, -0.42476765,  0.76464379, -0.23199439],
        [-0.50507589, -0.54267519, -0.64193252, -0.19576676],
        [-0.20612674,  0.54869183, -0.05515612, -0.80833585],
        [-0.72203822,  0.4733005 ,  0.01415338,  0.50442752]]))

In [27]:
# Berechnung der Eigenvektoren alle Eigenwerte
for i in res:
    print(Eigenvektor(i,A))

FiniteSet((0, 0, 0, 0))
FiniteSet((0, 0, 0, 0))
FiniteSet((0, 0, 0, 0))
FiniteSet((0, 0, 0, 0))


In [205]:
a,b,c,d = sp.symbols('a b c d')
sp.solve((A - (res[0]*np.eye(4)))*sp.Matrix([[a],[b],[c],[d]]))

{a: 0.0, b: 0.0, c: 0.0, d: 0.0}